<a href="https://colab.research.google.com/github/hwaraha/Chapter11/blob/main/LAB11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
#LAB 11-1
#1
import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
for i in range(10):
  b= np.array([i])
b

array([9])

In [21]:
c = np.array([0,2,4,6,8])
c

array([0, 2, 4, 6, 8])

In [27]:
c = np.array([0,2,4,6,8])
c.shape

(5,)

In [26]:
c.ndim

1

In [28]:
c.dtype

dtype('int64')

In [29]:
c.size

8

In [31]:
c.itemsize

8

In [35]:
#LAB 11-2
#1
a = np.array([23, 45, 67, 7, 2, 30, 34, 82])
a.flatten()

array([23, 45, 67,  7,  2, 30, 34, 82])

In [39]:
print('최댓값 : ') 
a.max()

최댓값 : 


82

In [ ]:
a.min()

In [36]:
a.mean()

36.25

In [43]:
b = np.random.randint(0, 99, size = 10)
print('b =', b)

b = [56 30 88  8 70 89 21 15 59 75]


In [ ]:
b.max()

In [ ]:
b.mean()

In [ ]:
b.min()

In [48]:
c = np.append(a,b)
print('c =', c)

c = [23 45 67  7  2 30 34 82 56 30 88  8 70 89 21 15 59 75]


In [71]:
#LAB 11-3
#1
c = np.array([1,2,3])
d = np.array([[4,5,6],[7,8,9]])
a = np.append([c], d, axis = 0)
print(a)
x = np.array([2,2,2])
y = np.array([[2,2,2],[2,2,2]])
b = np.append([x], y, axis = 0)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [74]:
a + b

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a - b

In [ ]:
a * b

In [ ]:
a / b

In [ ]:
a @ b

In [ ]:
a ** 2

In [77]:
#LAB 11-4
#1
a1 = np.full((3,3), 2)
print('a1 =', a1)

a1 = [[2 2 2]
 [2 2 2]
 [2 2 2]]


In [83]:
a2 = np.arange(1, 13)
print('a2 =', a2)

a2 = [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [88]:
a3 = np.arange(0, 50, 3)
print('a3 =', a3)

a3 = [ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]


In [94]:
a4 = np.arange(0, 25, 5)
print('a4 =', a4)

a4 = [ 0  5 10 15 20]


In [ ]:
a1 =  np.arange(1,13).reshape(4,3)
a1

In [120]:
#lAB 11-6
#1
b = np.random.randint(1, 101)
b

31

In [127]:
#lAB 11-7
#1
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.arange(0, 10, 2)
b

array([0, 2, 4, 6, 8])